package com.example.Student_Library_Management_System.Services;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    StudentRepository studentRepository;

    public String createStudent(Student student){
        //student from postman is already the basics attributes set

        //card should be autogenerated when createStudent is called
        Card card=new Card();
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student);


        //lets go to student
        student.setCard(card);

        //if there was a unidirectional we have tosave both of them
        //as we r using bidirectional card will be automatically saved


        studentRepository.save(student);

        //by ascading effects child will be automatically saved


        return "Student and card added";
    }
}
